<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="tadeo_ecar_base">
    
    <!-- Joint que conecta base_footprint con el chasis principal -->
    <joint name="base_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Link del chasis principal -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
        <geometry>
          <!-- NO QUITAR STL - requerido por el usuario -->
          <mesh filename="package://tadeo_ecar_description/meshes/chassis/chasis_base.stl" scale="1 1 1"/>
        </geometry>
        <material name="blue"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
        <geometry>
          <!-- NO QUITAR STL - requerido por el usuario -->
          <mesh filename="package://tadeo_ecar_description/meshes/chassis/chasis_base.stl" scale="1 1 1"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
        <mass value="50.0"/>
        <inertia ixx="4.0" ixy="0.0" ixz="0.0" 
                 iyy="4.0" iyz="0.0" 
                 izz="2.0"/>
      </inertial>
    </link>

    <!-- Joint que conecta base_link con chasis2 -->
    <joint name="chasis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chasis_link"/>
      <origin xyz="0 0 ${chassis_height + 0.05}" rpy="0 0 0"/>
    </joint>

    <!-- Link del chasis superior (chasis2) -->
    <link name="chasis_link">
      <visual>
        <origin xyz="-0.49 0.39 ${-chassis_z_offset-0.029}" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <!-- NO QUITAR STL - requerido por el usuario -->
          <mesh filename="package://tadeo_ecar_description/meshes/chassis/chasis.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="red"/>
      </visual>
      
      <collision>
        <origin xyz="-0.49 0.39 ${-chassis_z_offset-0.029}" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <!-- NO QUITAR STL - requerido por el usuario -->
          <mesh filename="package://tadeo_ecar_description/meshes/chassis/chasis.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="20.0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
                 iyy="1.0" iyz="0.0" 
                 izz="0.5"/>
      </inertial>
    </link>

    <!-- ========== SENSORES ========== -->
    
    <!-- Joint para cámara -->
    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin xyz="0.476 0 ${chassis_height + chassis_z_offset + camera_z_offset + 0.15}" rpy="0 0 0"/>
    </joint>

    <!-- Link de cámara -->
    <link name="camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
                 iyy="0.001" iyz="0.0" 
                 izz="0.001"/>
      </inertial>
    </link>

    <!-- Joint para LiDAR -->
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="lidar_link"/>
      <origin xyz="0.6 0 ${chassis_height - chassis_z_offset + lidar_height}" rpy="0 0 0"/>
    </joint>

    <!-- Link de LiDAR -->
    <link name="lidar_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
        <material name="dark_gray"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.2"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
                 iyy="0.001" iyz="0.0" 
                 izz="0.001"/>
      </inertial>
    </link>

    <!-- Joint para IMU -->
    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 ${chassis_height + chassis_z_offset + 0.05}" rpy="0 0 0"/>
    </joint>

    <!-- Link de IMU -->
    <link name="imu_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.01"/>
        </geometry>
        <material name="green"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.01"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
                 iyy="0.0001" iyz="0.0" 
                 izz="0.0001"/>
      </inertial>
    </link>

  </xacro:macro>

</robot>